---
apiVersion: v1
kind: Service
metadata:
  name: directorysearch-consumer
  namespace: app-dev
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: directorysearch-consumer
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: directorysearch-consumer-v1
  namespace: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directorysearch-consumer
      version: v1
  template:
    metadata:
      labels:
        app: directorysearch-consumer
        version: v1
    spec:
      containers:
        - name: app
          image: 246818788759.dkr.ecr.us-west-2.amazonaws.com/k8infra:color
          ports:
            - containerPort: 8080
          env:
            - name: "COLOR"
              value: "I am directory consumer"
