apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
 name: java-hello-world-route
 namespace: app-dev
spec:
  httpRoute:
    match:
      prefix: "/"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: helloworld